### ISSUE TITLE
Incorrect calculation of global mean

### ISSUE THREAD

**Issue by ad-si** [Aadv1k/deimos#1]
https://github.com/Aadv1k/deimos/blob/3a6f96e29fa1825c2f11b363606a931cdb8f9586/src/thresholding/otsu.c#L37

It should be the mean of the entire histogram, not just the cumulative mean up to the current threshold. You can correct this by calculating `globalMean` before the loop and using it inside the loop:
```c
for (unsigned int i = 0; i < GRAYSCALE; i++) {
  globalMean += i * normHistogram[i];
}

for (int i = 0; i < GRAYSCALE; i++) {
…
```

**Comment by Aadv1k** [comment]
DANG! No wonder the outputs generated from Otsu's threshold were so bad—I had completely forgotten about this repository, haha.

Thank you so much for pointing this out. Massive respect. Hope you have a great day and an amazing New Year (in advance). Cheers!

Best,
Aadvik

**Comment by ad-si** [comment]
Thanks, happy new year as well! 😊

You should reactivate the repository! I was looking for a clean C library for image manipulation and this was the best one I could find. The computer vision guide looks also nice so far. Would be a great resource if finished!

**Comment by Aadv1k** [comment]
Oh, man, thank you so much. It’s a massive compliment when another dev likes your project. Sure! Honestly I’ll probably spend some time with this library this year trying to get more stuff working. So glad you liked it. Cheers man!
